[package]
name = "lorikeet"
version = "0.10.0"
authors = ["cetra3 <cetra3@hotmail.com>"]
license = "MIT/Apache-2.0"
description = "a parallel test runner for devops"
repository = "https://github.com/cetra3/lorikeet"
readme = "README.md"
edition = "2018"

[dependencies]
petgraph = "0.4.13"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8.9"
linked-hash-map = { version = "0.5.2", features = ["serde_impl"] }
tera = "0.11.3"
structopt = "0.2.18"
threadpool = "1.7.1"
log = "0.4.7"
colored = "1.8"
atty = "0.2.12"
regex = "1.1.9"
env_logger = "0.6.2"
reqwest = "0.9.18"
chrono = { version = "0.4.7", features = ["serde"] }
lazy_static = "1.0.0"
chashmap = "2.2.2"
hostname = "0.1.5"
sys-info = "0.5.7"
openssl-probe = "0.1.2"
jmespath = "0.2.0"
failure = "0.1.5"
quick-xml = "0.15.0"
cookie = "0.12.0"
