[package]
name = "lorikeet"
version = "0.8.1"
authors = ["cetra3 <cetra3@hotmail.com>"]
license = "MIT/Apache-2.0"
description = "a parallel test runner for devops"
repository = "https://github.com/cetra3/lorikeet"
readme = "README.md"

[dependencies]
petgraph = "0.4.13"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
linked-hash-map = { version = "0.5.1", features = ["serde_impl"] }
tera = "0.11.2"
structopt = "0.2.2"
threadpool = "1.7.1"
log = "0.4.1"
term-painter = "0.2.4"
isatty = "0.1.6"
regex = "0.2.6"
env_logger = "0.5.3"
reqwest = "0.8.4"
hyper = "0.11.18"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.0.0"
chashmap = "2.2.0"
hostname = "0.1.4"
sys-info = "0.5.6"
openssl-probe = "0.1.2"
jmespath = "0.2.0"
failure = "0.1.1"
quick-xml = "0.12.0"