[package]
name = "lorikeet"
version = "0.3.1"
authors = ["cetra3 <cetra3@hotmail.com>"]
license = "MIT/Apache-2.0"
description = "a parallel test runner for devops"
repository = "https://github.com/cetra3/lorikeet"

[dependencies]
petgraph = "0.4.3"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
linked-hash-map = { version = "0.5", features = ["serde_impl"] }
tera = "0.10.8"
structopt = "0.1.0"
structopt-derive = "0.1.0"
threadpool = "1.4.1"
log = "0.3.8"
term-painter = "0.2.3"
isatty = "0.1"
regex = "0.2"
env_logger = "0.4.3"
reqwest = "0.7"
hyper = "0.11"
chrono = "0.4.0"
lazy_static = "0.2.8"
chashmap = "2.2.0"
